# Project Information
site_name: ARO Workshop Atlanta
site_url: https://ws.mobb.cloud/
site_description: A choose-your-own-adventure workshop for Operations and Development teams on ARO.
site_author: Red Hat

# Repository
repo_name: rh-mobb/aro-hackathon-content
repo_url: https://github.com/rh-mobb/aro-hackathon-content

# Nav Menu Definition
nav:
  - Welcome: index.md
  - Environment Setup: setup/environment.md
  - Access Your Cluster: setup/access-cluster.md
  - Day Two ARO Operations:
    - Managing Cluster Upgrades: ops/day2/upgrades.md
    - Managing Worker Nodes: ops/day2/scaling-nodes.md
    - Cluster Autoscaling: ops/day2/autoscaling.md
    - Labeling Nodes: ops/day2/labels.md
  - Azure Service Operator (ASO):
    - Deploy the Azure Service Operator: ops/aso/deploy.md
    - Deploy an Azure Service using ASO: ops/aso/app.md
  - Azure Front Door:
    - Create a Private Ingress Controller: ops/afd/private-ingress.md
    - Configure Azure Front Door: ops/afd/configure.md
  - Deploy and Expose an App:
    - Deploy the App: app/deploy.md
    - Expose the App with Front Door: app/afd.md
    - Automate Deploying the App: app/cicd.md
  - Make an App Resilient: app/resilience.md
  - Azure Arc: 
    - Connect Azure Arc with ARO: ops/arc/integration.md
    - Enable Azure Arc Observability: ops/arc/observability.md
    - Integrate Azure Key Vault: ops/arc/key-vault.md
  - Service Mesh:
    - Service Mesh: service-mesh/introduction.md
    - Deploy Service Mesh Operator: service-mesh/install.md
    - Deploy Control Plane: service-mesh/deploy-control-plane.md
    - Deploy Workloads: service-mesh/deploy-workload.md
    - Deploy Weighted Load Balancing: service-mesh/weighted-routing.md
    - Access Kiali Dashboard: service-mesh/kiali.md


# Theme Configuration
theme:
  features:
    - content.code.annotate
  name: material
  language: 'en'
  palette:
    primary: black
    accent: red
  font:
    text: Overpass
    code: Overpass Mono
  logo: favicon.ico
  favicon: favicon.ico
docs_dir: aro-content

# plugins
plugins:
- section-index

# Extensions
markdown_extensions:
  - abbr
  - toc:
      permalink: "#"
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'aro-content/assets/'

extra_css:
  - assets/css/custom.css

# Google Analytics
