# Project Information
site_name: ARO Workshop Atlanta
site_url: https://rh-mobb.github.io/aro-hackathon-content
site_description: A choose-your-own-adventure workshop for Operations and Development teams on ARO.
site_author: Red Hat

# Repository
repo_name: rh-mobb/aro-hackathon-content
repo_url: https://github.com/rh-mobb/aro-hackathon-content

# Nav Menu Definition
nav:
  - Welcome: index.md
  - Environment Setup: setup/1-environment-setup.md
  - Access Your Cluster: setup/3-access-cluster.md
  - Managing Cluster Upgrades: ops/2-1-upgrades.md
  - Managing Worker Nodes: ops/2-2-worker-nodes.md
  - Cluster Autoscaling: ops/2-3-autoscaling.md
  - Operations:
    - ARO Day 2 Operations:


      - Labeling Nodes: ops/2-4-label-nodes.md
    - Azure Front Door:
      - Create a Private Ingress Controller: ops/6-private-ingress.md
      - Configure Azure Front Door: ops/7-front-door.md
    - Azure Service Operator:
      - Deploy ASO: ops/3-deploy-azure-service-operator.md
      - Deploy an Azure Service using ASO: ops/4-1-deploy-azure-votes-app.md
    - Azure ARC Integration: ops/5-arc-integration.md
  - Development:
    - home_pages/development/index.md
    - Deploy and Expose an App:
      - Deploy the App: app/2A-deploy-app.md
      - Expose the App with Front Door: app/2B-deploy-app.md
      - Automate Deploying the App: app/2C-deploy-app.md
    - Make Applications Resilient: app/3-scale-app.md
    - Service Mesh:
      # - Service Mesh: service-meshv2/00-introduction.md
      - Deploy Service Mesh Operator: service-meshv2/0-infrastructure_operator_install.md
      - Deploy Control Plane: service-meshv2/1-deploy-control-plane.md
      - Deploy Workloads: service-meshv2/2-deplying-workloads.md
      - Deploy Weighted Load Balancing: service-meshv2/3-weighted-routing.md
      - Access Kiali Dashboard: service-meshv2/access_kiali_dashboard.md


# Theme Configuration
theme:
  features:
    - content.code.annotate
  name: material
  language: 'en'
  palette:
    primary: black
    accent: red
  font:
    text: Overpass
    code: Overpass Mono
  logo: favicon.ico
  favicon: favicon.ico
docs_dir: aro-content

# plugins
plugins:
- section-index

# Extensions
markdown_extensions:
  - abbr
  - toc:
      permalink: "#"
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'aro-content/assets/'

extra_css:
  - assets/css/custom.css

# Google Analytics
