# Project Information
site_name: ARO Hack-A-Thon
site_url: https://rh-mobb.github.io/aro-hackathon-content
site_description: A choose-your-own-adventure workshop for Operations and Development teams on ARO.
site_author: Red Hat

# Repository
repo_name: rh-mobb/aro-hackathon-content
repo_url: https://github.com/rh-mobb/aro-hackathon-content

# Nav Menu Definition
nav:
  - Home: index.md
  - Workshop Setup: general/1-workshop-setup.md
  - Operations:
    - Setup: ops/1-account-setup.md
    - ARO Day 2 Operations: ops/2-aro-day-2-operations.md
    - Azure Service Operator: ops/3-deploy-azure-service-operator.md
    - Azure ARC Integration: ops/5-arc-integration.md
  - App Dev:
    - Setup: app/1-account-setup.md
    - Deploy and Expose and App: app/2-deploy-app.md
    - Make Applications Resilient: app/3-scale-app.md


# Theme Configuration
theme:
  name: material
  language: 'en'
  palette:
    primary: black
    accent: red
  font:
    text: Overpass
    code: Overpass Mono
  logo: favicon.ico
  favicon: favicon.ico
docs_dir: aro-content

# Extensions
markdown_extensions:
  - abbr
  - toc:
      permalink: "#"
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

# Google Analytics
